name: VuePress CI

on:
  push:
    branches:
      - main  # 仅监听main分支
      - '!gh-pages'  # 排除gh-pages分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm install vuepress@1.9.10
          npm install
      - name: Build
        run: npx vuepress build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/.vuepress/dist
            # # 关键修复：指定目标分支
            # destination_branch: gh-pages
            # # 清空目标分支内容
            # force_orphan: true